version: '3'
services:
  tallerdocker:
    build: "TallerDocker/."
    ports:
      - "9091:8080"
    networks: 
      - "service-compose-net"
  routerservice:
    build: "routerservice/."
    ports:
      - "9092:9999"
    networks: 
      - "service-compose-net"
  registryservice:
    build: "registryservice/."
    ports:
      - "9093:9998"
    networks: 
      - "service-compose-net"
networks:
  service-compose-net:
    driver: bridge

